### ISSUE TITLE
undefined method `add_teardown_hook' for ActionDispatch::IntegrationTest:Class

### ISSUE THREAD

**Issue by kerryb** [mattheworiordan/capybara-screenshot#5]
After updating to 0.1.5, I get this error on initialisation, from `lib/capybara-screenshot/minitest.rb:4`.

I'm using Rails 3.1.3 and Ruby 1.9.2, but the project was created with `--skip-active-record --skip-test-unit`, in case that makes a difference.

Perhaps it would be safer to check that `ActionDispatch::IntegrationTest` is not only defined, but also responds to `#add_teardown_hook`.
